server:
  port: 8061

spring:
  application:
    name: matching-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: com.tushargautamtgs.matching_service.event
        spring.json.value.default.type: com.tushargautamtgs.matching_service.event.RideRequestedEvent

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: true

# üîê SERVICE-TO-SERVICE SECURITY
security:
  jwt:
    secret: TgsAuthServiceJwtKey_2025_Secure!
logging:
  level:
    com.tushargautamtgs.matching_service: DEBUG
    org.apache.kafka: INFO
