server:
  port: 8087

spring:
  application:
    name: matching-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: com.tushargautamtgs.matching_service.event
        spring.json.value.default.type: com.tushargautamtgs.matching_service.event.RideRequestedEvent

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: true

# üîê SERVICE-TO-SERVICE SECURITY (NEW)
security:
  service-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtYXRjaGluZy1zZXJ2aWNlIiwiYXV0aG9yaXRpZXMiOlsiU0VSVklDRV9NQVRDSElORyJdLCJpYXQiOjE3NjYyNTYwMDAsImV4cCI6MTc2NjM0MjQwMH0.1AyMPHxW8PnehfoiJ2rpDObyCOKrgu5aEOmwNSHMWuU

logging:
  level:
    com.tushargautamtgs.matching_service: DEBUG
    org.apache.kafka: INFO
